### PR TITLE
Manage test execution with flag

### PR DESCRIPTION
**Pull request by crane-hiromu**
Thank you for a very nice library.
I have a suggestion to make it more user friendly.

In many implementations, such as SDKs for advertising, the tests are managed by flags.
I think this implementation is more Swifty.

```.swift
@main
struct MyApp: App {
    
    init() {
        PlaygroundTesterConfigurator.isTesting = false
    }
    
    var body: some Scene {
        WindowGroup {
            PlaygroundTesterView {
                // your view
            }
        }
    }
}
```

If you don't mind, please adopt this idea.
Also, it would be helpful if you could revise my comments in the readme to be more appropriate.

If it's not desirable, I'll withdraw the Pull Request.

### CODE REVIEW

**Review by Losiowaty — COMMENTED** [review]
Hi!
Thank you for your contribution!
I generally like the idea, adding the `Configuration` enum opens up possibilities to add different flags/options there - like for example restricting test to run to only specific class.

My small problem with this is that it's a breaking change, so current users will get a compilation error when updating 😓 
Unfortunately I don't think this can be bypassed at this moment.

**Comment by crane-hiromu** [comment]
Thank you for reacting and reviewing!
I fixed them.

<br>

> My small problem with this is that it's a breaking change, so current users will get a compilation error when updating 😓
> Unfortunately I don't think this can be bypassed at this moment.

Oh, I didn't take it into consideration.
I have another idea.

Keep the old code for compatibility with older versions.
However, a deprecation warning must be issued.

```.swift
@available(*, deprecated, message: "deprecated message ...") // here
public struct PlaygroundTesterView: View {

  public init() {}

  public var body: some View {
    TestingView()
  }
}
```

Then change the name of the newly added class.

```.swift
public struct PlaygroundControlTesterView<Content: View>: View {
  let content: Content
    
  /* omitted */
}
```
（I couldn't come up with a good name for class...）

This will solve your concerns.
How do you think?

**Comment by Losiowaty** [comment]
@crane-hiromu
Sorry, was preoccupied a little bit.

Yeah, that would work!
For class name - what do you think about `PlaygroundTesterWrapperView`?
And for the deprecation message something like this : 
``This view is being deprecated - please switch to `PlaygroundTesterWrapperView` and refer to Readme on new appraoach. This view may be removed in future versions.``

**Comment by crane-hiromu** [comment]
Thanks!
Your opinion has been taken into pull request.
Please review it :)

**Review by Losiowaty — APPROVED** [review]

**Comment by Losiowaty** [comment]
@crane-hiromu 
I just create a release `0.3.0` with your changes :)

**Comment by crane-hiromu** [comment]
Thanks a lot!

**Pull request merged**
